apiVersion: v1
kind: ConfigMap
metadata:
  name: time-page
  namespace: http-ns
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Static Time</title>
      </head>
      <body>
        <h1>Generated at:</h1>
        <p>{{GENERATED_AT}}</p>
      </body>
    </html>
